apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
 name: first-pool
 namespace: metallb-system
 annotations:
   "helm.sh/hook": "post-install"
   "helm.sh/hook-weight": "0"
spec:
 addresses:
 - IPPLACEHOLDER - IPPLACEHOLDER
