apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: actix-sgx
spec:
  template:
    spec:
    # uncomment the block below, if you have enabled node Selector and change label:value
    #  nodeSelector:
    #    label:value
      containers:
        - image: dennisfaut/actix-sgx
          ports:
            - containerPort: 8080
          imagePullPolicy: Always
          env:
          - name: ENCLAIVE_SERVER
            value: "https://enclaive-vault-sgx.vault.svc.cluster.local:8200"
          - name: domain
            value: DOMAINPLACEHOLDER
          volumeMounts:
          - mountPath: /dev/sgx/enclave
            name: dev-sgx-enclave
          - mountPath: /dev/sgx_enclave
            name: dev-sgx-enclave
          - mountPath: /dev/sgx_provision
            name: dev-sgx-provision
          securityContext:
            privileged: true
      volumes:
      - name: dev-sgx-provision
        hostPath:
          path: /dev/sgx_provision
      - name: dev-sgx-enclave
        hostPath:
          path: /dev/sgx_enclave
